// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mychain/taskreg/v1/genesis.proto
package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	"google.golang.org/protobuf/encoding/protowire"
	math "math"
)

var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type GenesisState struct {
	Tasks      []Task `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks"`
	NextTaskId uint64 `protobuf:"varint,2,opt,name=next_task_id,json=nextTaskId,proto3" json:"next_task_id,omitempty"`
}

func (m *GenesisState) Reset()                       { *m = GenesisState{} }
func (m *GenesisState) String() string                { return proto.CompactTextString(m) }
func (m *GenesisState) ProtoMessage()                 {}
func (*GenesisState) Descriptor() ([]byte, []int)     { return fileDescriptor_genesis, []int{0} }

func (m *GenesisState) GetTasks() []Task {
	if m != nil {
		return m.Tasks
	}
	return nil
}

func (m *GenesisState) GetNextTaskId() uint64 {
	if m != nil {
		return m.NextTaskId
	}
	return 0
}

func (m *GenesisState) Marshal() ([]byte, error) {
	b := make([]byte, 0, m.Size())
	for i := range m.Tasks {
		taskBz, err := m.Tasks[i].Marshal()
		if err != nil {
			return nil, err
		}
		b = protowire.AppendTag(b, 1, protowire.BytesType)
		b = protowire.AppendBytes(b, taskBz)
	}
	b = appendUint64(b, 2, m.NextTaskId)
	return b, nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	bz, err := m.Marshal()
	if err != nil {
		return 0, err
	}
	copy(dAtA, bz)
	return len(bz), nil
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	bz, err := m.Marshal()
	if err != nil {
		return 0, err
	}
	copy(dAtA[len(dAtA)-len(bz):], bz)
	return len(bz), nil
}

func (m *GenesisState) Size() int {
	n := 0
	for i := range m.Tasks {
		taskSize := m.Tasks[i].Size()
		n += protowire.SizeTag(1) + protowire.SizeBytes(taskSize)
	}
	n += sizeUint64(2, m.NextTaskId)
	return n
}

func (m *GenesisState) Unmarshal(b []byte) error {
	for len(b) > 0 {
		num, typ, n := protowire.ConsumeTag(b)
		if n < 0 {
			return fmt.Errorf("bad tag")
		}
		b = b[n:]
		switch num {
		case 1:
			bz, n := protowire.ConsumeBytes(b)
			if n < 0 {
				return fmt.Errorf("bad bytes")
			}
			var task Task
			if err := task.Unmarshal(bz); err != nil {
				return err
			}
			m.Tasks = append(m.Tasks, task)
			b = b[n:]
		case 2:
			v, n := protowire.ConsumeVarint(b)
			if n < 0 {
				return fmt.Errorf("bad varint")
			}
			m.NextTaskId = v
			b = b[n:]
		default:
			var err error
			b, err = skipField(b, typ)
			if err != nil {
				return err
			}
		}
	}
	return nil
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "mychain.taskreg.v1.GenesisState")
}
