// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mychain/taskreg/v1/query.proto
package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	"google.golang.org/protobuf/encoding/protowire"
	math "math"
)

var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// QueryTaskRequest
type QueryTaskRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryTaskRequest) Reset()                       { *m = QueryTaskRequest{} }
func (m *QueryTaskRequest) String() string                { return proto.CompactTextString(m) }
func (m *QueryTaskRequest) ProtoMessage()                 {}
func (*QueryTaskRequest) Descriptor() ([]byte, []int)     { return fileDescriptor_query, []int{0} }

func (m *QueryTaskRequest) GetId() uint64 { return m.Id }

func (m *QueryTaskRequest) Marshal() ([]byte, error) {
	b := make([]byte, 0, m.Size())
	b = appendUint64(b, 1, m.Id)
	return b, nil
}
func (m *QueryTaskRequest) MarshalTo(dAtA []byte) (int, error) {
	bz, err := m.Marshal()
	if err != nil {
		return 0, err
	}
	copy(dAtA, bz)
	return len(bz), nil
}
func (m *QueryTaskRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	bz, err := m.Marshal()
	if err != nil {
		return 0, err
	}
	copy(dAtA[len(dAtA)-len(bz):], bz)
	return len(bz), nil
}
func (m *QueryTaskRequest) Size() int {
	return sizeUint64(1, m.Id)
}
func (m *QueryTaskRequest) Unmarshal(b []byte) error {
	for len(b) > 0 {
		num, typ, n := protowire.ConsumeTag(b)
		if n < 0 {
			return fmt.Errorf("bad tag")
		}
		b = b[n:]
		switch num {
		case 1:
			v, n := protowire.ConsumeVarint(b)
			if n < 0 {
				return fmt.Errorf("bad varint")
			}
			m.Id = v
			b = b[n:]
		default:
			var err error
			b, err = skipField(b, typ)
			if err != nil {
				return err
			}
		}
	}
	return nil
}

// QueryTaskResponse
type QueryTaskResponse struct {
	Task Task `protobuf:"bytes,1,opt,name=task,proto3" json:"task"`
}

func (m *QueryTaskResponse) Reset()                       { *m = QueryTaskResponse{} }
func (m *QueryTaskResponse) String() string                { return proto.CompactTextString(m) }
func (m *QueryTaskResponse) ProtoMessage()                 {}
func (*QueryTaskResponse) Descriptor() ([]byte, []int)     { return fileDescriptor_query, []int{1} }

func (m *QueryTaskResponse) GetTask() Task { return m.Task }

func (m *QueryTaskResponse) Marshal() ([]byte, error) {
	b := make([]byte, 0, m.Size())
	taskBz, err := m.Task.Marshal()
	if err != nil {
		return nil, err
	}
	if len(taskBz) > 0 {
		b = protowire.AppendTag(b, 1, protowire.BytesType)
		b = protowire.AppendBytes(b, taskBz)
	}
	return b, nil
}
func (m *QueryTaskResponse) MarshalTo(dAtA []byte) (int, error) {
	bz, err := m.Marshal()
	if err != nil {
		return 0, err
	}
	copy(dAtA, bz)
	return len(bz), nil
}
func (m *QueryTaskResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	bz, err := m.Marshal()
	if err != nil {
		return 0, err
	}
	copy(dAtA[len(dAtA)-len(bz):], bz)
	return len(bz), nil
}
func (m *QueryTaskResponse) Size() int {
	taskSize := m.Task.Size()
	if taskSize == 0 {
		return 0
	}
	return protowire.SizeTag(1) + protowire.SizeBytes(taskSize)
}
func (m *QueryTaskResponse) Unmarshal(b []byte) error {
	for len(b) > 0 {
		num, typ, n := protowire.ConsumeTag(b)
		if n < 0 {
			return fmt.Errorf("bad tag")
		}
		b = b[n:]
		switch num {
		case 1:
			bz, n := protowire.ConsumeBytes(b)
			if n < 0 {
				return fmt.Errorf("bad bytes")
			}
			if err := m.Task.Unmarshal(bz); err != nil {
				return err
			}
			b = b[n:]
		default:
			var err error
			b, err = skipField(b, typ)
			if err != nil {
				return err
			}
		}
	}
	return nil
}

// QueryListTasksRequest
type QueryListTasksRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryListTasksRequest) Reset()                       { *m = QueryListTasksRequest{} }
func (m *QueryListTasksRequest) String() string                { return proto.CompactTextString(m) }
func (m *QueryListTasksRequest) ProtoMessage()                 {}
func (*QueryListTasksRequest) Descriptor() ([]byte, []int)     { return fileDescriptor_query, []int{2} }

func (m *QueryListTasksRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func (m *QueryListTasksRequest) Marshal() ([]byte, error) {
	b := make([]byte, 0, m.Size())
	if m.Pagination != nil {
		pagBz, err := m.Pagination.Marshal()
		if err != nil {
			return nil, err
		}
		if len(pagBz) > 0 {
			b = protowire.AppendTag(b, 1, protowire.BytesType)
			b = protowire.AppendBytes(b, pagBz)
		}
	}
	return b, nil
}
func (m *QueryListTasksRequest) MarshalTo(dAtA []byte) (int, error) {
	bz, err := m.Marshal()
	if err != nil {
		return 0, err
	}
	copy(dAtA, bz)
	return len(bz), nil
}
func (m *QueryListTasksRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	bz, err := m.Marshal()
	if err != nil {
		return 0, err
	}
	copy(dAtA[len(dAtA)-len(bz):], bz)
	return len(bz), nil
}
func (m *QueryListTasksRequest) Size() int {
	if m.Pagination == nil {
		return 0
	}
	pagSize := m.Pagination.Size()
	if pagSize == 0 {
		return 0
	}
	return protowire.SizeTag(1) + protowire.SizeBytes(pagSize)
}
func (m *QueryListTasksRequest) Unmarshal(b []byte) error {
	for len(b) > 0 {
		num, typ, n := protowire.ConsumeTag(b)
		if n < 0 {
			return fmt.Errorf("bad tag")
		}
		b = b[n:]
		switch num {
		case 1:
			bz, n := protowire.ConsumeBytes(b)
			if n < 0 {
				return fmt.Errorf("bad bytes")
			}
			m.Pagination = &query.PageRequest{}
			if err := m.Pagination.Unmarshal(bz); err != nil {
				return err
			}
			b = b[n:]
		default:
			var err error
			b, err = skipField(b, typ)
			if err != nil {
				return err
			}
		}
	}
	return nil
}

// QueryListTasksResponse
type QueryListTasksResponse struct {
	Tasks      []Task              `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryListTasksResponse) Reset()                       { *m = QueryListTasksResponse{} }
func (m *QueryListTasksResponse) String() string                { return proto.CompactTextString(m) }
func (m *QueryListTasksResponse) ProtoMessage()                 {}
func (*QueryListTasksResponse) Descriptor() ([]byte, []int)     { return fileDescriptor_query, []int{3} }

func (m *QueryListTasksResponse) GetTasks() []Task {
	if m != nil {
		return m.Tasks
	}
	return nil
}

func (m *QueryListTasksResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func (m *QueryListTasksResponse) Marshal() ([]byte, error) {
	b := make([]byte, 0, m.Size())
	for i := range m.Tasks {
		taskBz, err := m.Tasks[i].Marshal()
		if err != nil {
			return nil, err
		}
		b = protowire.AppendTag(b, 1, protowire.BytesType)
		b = protowire.AppendBytes(b, taskBz)
	}
	if m.Pagination != nil {
		pagBz, err := m.Pagination.Marshal()
		if err != nil {
			return nil, err
		}
		if len(pagBz) > 0 {
			b = protowire.AppendTag(b, 2, protowire.BytesType)
			b = protowire.AppendBytes(b, pagBz)
		}
	}
	return b, nil
}
func (m *QueryListTasksResponse) MarshalTo(dAtA []byte) (int, error) {
	bz, err := m.Marshal()
	if err != nil {
		return 0, err
	}
	copy(dAtA, bz)
	return len(bz), nil
}
func (m *QueryListTasksResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	bz, err := m.Marshal()
	if err != nil {
		return 0, err
	}
	copy(dAtA[len(dAtA)-len(bz):], bz)
	return len(bz), nil
}
func (m *QueryListTasksResponse) Size() int {
	n := 0
	for i := range m.Tasks {
		taskSize := m.Tasks[i].Size()
		n += protowire.SizeTag(1) + protowire.SizeBytes(taskSize)
	}
	if m.Pagination != nil {
		pagSize := m.Pagination.Size()
		if pagSize > 0 {
			n += protowire.SizeTag(2) + protowire.SizeBytes(pagSize)
		}
	}
	return n
}
func (m *QueryListTasksResponse) Unmarshal(b []byte) error {
	for len(b) > 0 {
		num, typ, n := protowire.ConsumeTag(b)
		if n < 0 {
			return fmt.Errorf("bad tag")
		}
		b = b[n:]
		switch num {
		case 1:
			bz, n := protowire.ConsumeBytes(b)
			if n < 0 {
				return fmt.Errorf("bad bytes")
			}
			var task Task
			if err := task.Unmarshal(bz); err != nil {
				return err
			}
			m.Tasks = append(m.Tasks, task)
			b = b[n:]
		case 2:
			bz, n := protowire.ConsumeBytes(b)
			if n < 0 {
				return fmt.Errorf("bad bytes")
			}
			m.Pagination = &query.PageResponse{}
			if err := m.Pagination.Unmarshal(bz); err != nil {
				return err
			}
			b = b[n:]
		default:
			var err error
			b, err = skipField(b, typ)
			if err != nil {
				return err
			}
		}
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryTaskRequest)(nil), "mychain.taskreg.v1.QueryTaskRequest")
	proto.RegisterType((*QueryTaskResponse)(nil), "mychain.taskreg.v1.QueryTaskResponse")
	proto.RegisterType((*QueryListTasksRequest)(nil), "mychain.taskreg.v1.QueryListTasksRequest")
	proto.RegisterType((*QueryListTasksResponse)(nil), "mychain.taskreg.v1.QueryListTasksResponse")
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	Task(context.Context, *QueryTaskRequest) (*QueryTaskResponse, error)
	ListTasks(context.Context, *QueryListTasksRequest) (*QueryListTasksResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct{}

func (*UnimplementedQueryServer) Task(context.Context, *QueryTaskRequest) (*QueryTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Task not implemented")
}
func (*UnimplementedQueryServer) ListTasks(context.Context, *QueryListTasksRequest) (*QueryListTasksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTasks not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Task_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Task(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mychain.taskreg.v1.Query/Task",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Task(ctx, req.(*QueryTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ListTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryListTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ListTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mychain.taskreg.v1.Query/ListTasks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ListTasks(ctx, req.(*QueryListTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mychain.taskreg.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Task",
			Handler:    _Query_Task_Handler,
		},
		{
			MethodName: "ListTasks",
			Handler:    _Query_ListTasks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mychain/taskreg/v1/query.proto",
}

// QueryClient is the client API for Query service.
type QueryClient interface {
	Task(ctx context.Context, in *QueryTaskRequest, opts ...grpc.CallOption) (*QueryTaskResponse, error)
	ListTasks(ctx context.Context, in *QueryListTasksRequest, opts ...grpc.CallOption) (*QueryListTasksResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Task(ctx context.Context, in *QueryTaskRequest, opts ...grpc.CallOption) (*QueryTaskResponse, error) {
	out := new(QueryTaskResponse)
	err := c.cc.Invoke(ctx, "/mychain.taskreg.v1.Query/Task", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ListTasks(ctx context.Context, in *QueryListTasksRequest, opts ...grpc.CallOption) (*QueryListTasksResponse, error) {
	out := new(QueryListTasksResponse)
	err := c.cc.Invoke(ctx, "/mychain.taskreg.v1.Query/ListTasks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}
