// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mychain/taskreg/v1/tx.proto
package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	"google.golang.org/protobuf/encoding/protowire"
	math "math"
)

var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// ---- protowire helpers ----
func appendString(b []byte, fieldNum protowire.Number, s string) []byte {
	if s == "" {
		return b
	}
	b = protowire.AppendTag(b, fieldNum, protowire.BytesType)
	b = protowire.AppendString(b, s)
	return b
}

func appendUint64(b []byte, fieldNum protowire.Number, v uint64) []byte {
	if v == 0 {
		return b
	}
	b = protowire.AppendTag(b, fieldNum, protowire.VarintType)
	b = protowire.AppendVarint(b, v)
	return b
}

func sizeString(fieldNum protowire.Number, s string) int {
	if s == "" {
		return 0
	}
	return protowire.SizeTag(fieldNum) + protowire.SizeBytes(len(s))
}

func sizeUint64(fieldNum protowire.Number, v uint64) int {
	if v == 0 {
		return 0
	}
	return protowire.SizeTag(fieldNum) + protowire.SizeVarint(v)
}

func skipField(b []byte, typ protowire.Type) ([]byte, error) {
	n := protowire.ConsumeFieldValue(protowire.Number(0), typ, b)
	if n < 0 {
		return nil, fmt.Errorf("invalid field")
	}
	return b[n:], nil
}

// ---- MsgCreateTask ----
type MsgCreateTask struct {
	Creator     string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Title       string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
}

func (m *MsgCreateTask) Reset()                       { *m = MsgCreateTask{} }
func (m *MsgCreateTask) String() string                { return fmt.Sprintf("MsgCreateTask{creator:%s}", m.Creator) }
func (m *MsgCreateTask) ProtoMessage()                 {}
func (*MsgCreateTask) Descriptor() ([]byte, []int)     { return fileDescriptor_tx, []int{0} }

func (m *MsgCreateTask) GetCreator() string     { return m.Creator }
func (m *MsgCreateTask) GetTitle() string        { return m.Title }
func (m *MsgCreateTask) GetDescription() string  { return m.Description }

func (m *MsgCreateTask) Marshal() ([]byte, error) {
	b := make([]byte, 0, m.Size())
	b = appendString(b, 1, m.Creator)
	b = appendString(b, 2, m.Title)
	b = appendString(b, 3, m.Description)
	return b, nil
}

func (m *MsgCreateTask) MarshalTo(dAtA []byte) (int, error) {
	bz, err := m.Marshal()
	if err != nil {
		return 0, err
	}
	copy(dAtA, bz)
	return len(bz), nil
}

func (m *MsgCreateTask) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	bz, err := m.Marshal()
	if err != nil {
		return 0, err
	}
	copy(dAtA[len(dAtA)-len(bz):], bz)
	return len(bz), nil
}

func (m *MsgCreateTask) Size() int {
	return sizeString(1, m.Creator) + sizeString(2, m.Title) + sizeString(3, m.Description)
}

func (m *MsgCreateTask) Unmarshal(b []byte) error {
	for len(b) > 0 {
		num, typ, n := protowire.ConsumeTag(b)
		if n < 0 {
			return fmt.Errorf("bad tag")
		}
		b = b[n:]
		switch num {
		case 1:
			v, n := protowire.ConsumeString(b)
			if n < 0 {
				return fmt.Errorf("bad string")
			}
			m.Creator = v
			b = b[n:]
		case 2:
			v, n := protowire.ConsumeString(b)
			if n < 0 {
				return fmt.Errorf("bad string")
			}
			m.Title = v
			b = b[n:]
		case 3:
			v, n := protowire.ConsumeString(b)
			if n < 0 {
				return fmt.Errorf("bad string")
			}
			m.Description = v
			b = b[n:]
		default:
			var err error
			b, err = skipField(b, typ)
			if err != nil {
				return err
			}
		}
	}
	return nil
}

// ---- MsgCreateTaskResponse ----
type MsgCreateTaskResponse struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MsgCreateTaskResponse) Reset()                       { *m = MsgCreateTaskResponse{} }
func (m *MsgCreateTaskResponse) String() string                { return fmt.Sprintf("MsgCreateTaskResponse{id:%d}", m.Id) }
func (m *MsgCreateTaskResponse) ProtoMessage()                 {}
func (*MsgCreateTaskResponse) Descriptor() ([]byte, []int)     { return fileDescriptor_tx, []int{1} }
func (m *MsgCreateTaskResponse) GetId() uint64  { return m.Id }

func (m *MsgCreateTaskResponse) Marshal() ([]byte, error) {
	b := make([]byte, 0, m.Size())
	b = appendUint64(b, 1, m.Id)
	return b, nil
}

func (m *MsgCreateTaskResponse) MarshalTo(dAtA []byte) (int, error) {
	bz, err := m.Marshal()
	if err != nil {
		return 0, err
	}
	copy(dAtA, bz)
	return len(bz), nil
}

func (m *MsgCreateTaskResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	bz, err := m.Marshal()
	if err != nil {
		return 0, err
	}
	copy(dAtA[len(dAtA)-len(bz):], bz)
	return len(bz), nil
}

func (m *MsgCreateTaskResponse) Size() int {
	return sizeUint64(1, m.Id)
}

func (m *MsgCreateTaskResponse) Unmarshal(b []byte) error {
	for len(b) > 0 {
		num, typ, n := protowire.ConsumeTag(b)
		if n < 0 {
			return fmt.Errorf("bad tag")
		}
		b = b[n:]
		switch num {
		case 1:
			v, n := protowire.ConsumeVarint(b)
			if n < 0 {
				return fmt.Errorf("bad varint")
			}
			m.Id = v
			b = b[n:]
		default:
			var err error
			b, err = skipField(b, typ)
			if err != nil {
				return err
			}
		}
	}
	return nil
}

// ---- MsgAssignTask ----
type MsgAssignTask struct {
	Creator  string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	TaskId   uint64 `protobuf:"varint,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Assignee string `protobuf:"bytes,3,opt,name=assignee,proto3" json:"assignee,omitempty"`
}

func (m *MsgAssignTask) Reset()                       { *m = MsgAssignTask{} }
func (m *MsgAssignTask) String() string                { return fmt.Sprintf("MsgAssignTask{creator:%s}", m.Creator) }
func (m *MsgAssignTask) ProtoMessage()                 {}
func (*MsgAssignTask) Descriptor() ([]byte, []int)     { return fileDescriptor_tx, []int{2} }

func (m *MsgAssignTask) GetCreator() string  { return m.Creator }
func (m *MsgAssignTask) GetTaskId() uint64   { return m.TaskId }
func (m *MsgAssignTask) GetAssignee() string { return m.Assignee }

func (m *MsgAssignTask) Marshal() ([]byte, error) {
	b := make([]byte, 0, m.Size())
	b = appendString(b, 1, m.Creator)
	b = appendUint64(b, 2, m.TaskId)
	b = appendString(b, 3, m.Assignee)
	return b, nil
}

func (m *MsgAssignTask) MarshalTo(dAtA []byte) (int, error) {
	bz, err := m.Marshal()
	if err != nil {
		return 0, err
	}
	copy(dAtA, bz)
	return len(bz), nil
}

func (m *MsgAssignTask) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	bz, err := m.Marshal()
	if err != nil {
		return 0, err
	}
	copy(dAtA[len(dAtA)-len(bz):], bz)
	return len(bz), nil
}

func (m *MsgAssignTask) Size() int {
	return sizeString(1, m.Creator) + sizeUint64(2, m.TaskId) + sizeString(3, m.Assignee)
}

func (m *MsgAssignTask) Unmarshal(b []byte) error {
	for len(b) > 0 {
		num, typ, n := protowire.ConsumeTag(b)
		if n < 0 {
			return fmt.Errorf("bad tag")
		}
		b = b[n:]
		switch num {
		case 1:
			v, n := protowire.ConsumeString(b)
			if n < 0 {
				return fmt.Errorf("bad string")
			}
			m.Creator = v
			b = b[n:]
		case 2:
			v, n := protowire.ConsumeVarint(b)
			if n < 0 {
				return fmt.Errorf("bad varint")
			}
			m.TaskId = v
			b = b[n:]
		case 3:
			v, n := protowire.ConsumeString(b)
			if n < 0 {
				return fmt.Errorf("bad string")
			}
			m.Assignee = v
			b = b[n:]
		default:
			var err error
			b, err = skipField(b, typ)
			if err != nil {
				return err
			}
		}
	}
	return nil
}

// ---- MsgAssignTaskResponse ----
type MsgAssignTaskResponse struct{}

func (m *MsgAssignTaskResponse) Reset()                       { *m = MsgAssignTaskResponse{} }
func (m *MsgAssignTaskResponse) String() string                { return "MsgAssignTaskResponse{}" }
func (m *MsgAssignTaskResponse) ProtoMessage()                 {}
func (*MsgAssignTaskResponse) Descriptor() ([]byte, []int)     { return fileDescriptor_tx, []int{3} }

func (m *MsgAssignTaskResponse) Marshal() ([]byte, error)               { return nil, nil }
func (m *MsgAssignTaskResponse) MarshalTo(dAtA []byte) (int, error)     { return 0, nil }
func (m *MsgAssignTaskResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) { return 0, nil }
func (m *MsgAssignTaskResponse) Size() int                              { return 0 }
func (m *MsgAssignTaskResponse) Unmarshal(_ []byte) error               { return nil }

// ---- MsgCompleteTask ----
type MsgCompleteTask struct {
	Assignee string `protobuf:"bytes,1,opt,name=assignee,proto3" json:"assignee,omitempty"`
	TaskId   uint64 `protobuf:"varint,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
}

func (m *MsgCompleteTask) Reset()                       { *m = MsgCompleteTask{} }
func (m *MsgCompleteTask) String() string                { return fmt.Sprintf("MsgCompleteTask{assignee:%s}", m.Assignee) }
func (m *MsgCompleteTask) ProtoMessage()                 {}
func (*MsgCompleteTask) Descriptor() ([]byte, []int)     { return fileDescriptor_tx, []int{4} }

func (m *MsgCompleteTask) GetAssignee() string { return m.Assignee }
func (m *MsgCompleteTask) GetTaskId() uint64   { return m.TaskId }

func (m *MsgCompleteTask) Marshal() ([]byte, error) {
	b := make([]byte, 0, m.Size())
	b = appendString(b, 1, m.Assignee)
	b = appendUint64(b, 2, m.TaskId)
	return b, nil
}

func (m *MsgCompleteTask) MarshalTo(dAtA []byte) (int, error) {
	bz, err := m.Marshal()
	if err != nil {
		return 0, err
	}
	copy(dAtA, bz)
	return len(bz), nil
}

func (m *MsgCompleteTask) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	bz, err := m.Marshal()
	if err != nil {
		return 0, err
	}
	copy(dAtA[len(dAtA)-len(bz):], bz)
	return len(bz), nil
}

func (m *MsgCompleteTask) Size() int {
	return sizeString(1, m.Assignee) + sizeUint64(2, m.TaskId)
}

func (m *MsgCompleteTask) Unmarshal(b []byte) error {
	for len(b) > 0 {
		num, typ, n := protowire.ConsumeTag(b)
		if n < 0 {
			return fmt.Errorf("bad tag")
		}
		b = b[n:]
		switch num {
		case 1:
			v, n := protowire.ConsumeString(b)
			if n < 0 {
				return fmt.Errorf("bad string")
			}
			m.Assignee = v
			b = b[n:]
		case 2:
			v, n := protowire.ConsumeVarint(b)
			if n < 0 {
				return fmt.Errorf("bad varint")
			}
			m.TaskId = v
			b = b[n:]
		default:
			var err error
			b, err = skipField(b, typ)
			if err != nil {
				return err
			}
		}
	}
	return nil
}

// ---- MsgCompleteTaskResponse ----
type MsgCompleteTaskResponse struct{}

func (m *MsgCompleteTaskResponse) Reset()                       { *m = MsgCompleteTaskResponse{} }
func (m *MsgCompleteTaskResponse) String() string                { return "MsgCompleteTaskResponse{}" }
func (m *MsgCompleteTaskResponse) ProtoMessage()                 {}
func (*MsgCompleteTaskResponse) Descriptor() ([]byte, []int)     { return fileDescriptor_tx, []int{5} }

func (m *MsgCompleteTaskResponse) Marshal() ([]byte, error)               { return nil, nil }
func (m *MsgCompleteTaskResponse) MarshalTo(dAtA []byte) (int, error)     { return 0, nil }
func (m *MsgCompleteTaskResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) { return 0, nil }
func (m *MsgCompleteTaskResponse) Size() int                              { return 0 }
func (m *MsgCompleteTaskResponse) Unmarshal(_ []byte) error               { return nil }

// ---- Registration ----
func init() {
	proto.RegisterType((*MsgCreateTask)(nil), "mychain.taskreg.v1.MsgCreateTask")
	proto.RegisterType((*MsgCreateTaskResponse)(nil), "mychain.taskreg.v1.MsgCreateTaskResponse")
	proto.RegisterType((*MsgAssignTask)(nil), "mychain.taskreg.v1.MsgAssignTask")
	proto.RegisterType((*MsgAssignTaskResponse)(nil), "mychain.taskreg.v1.MsgAssignTaskResponse")
	proto.RegisterType((*MsgCompleteTask)(nil), "mychain.taskreg.v1.MsgCompleteTask")
	proto.RegisterType((*MsgCompleteTaskResponse)(nil), "mychain.taskreg.v1.MsgCompleteTaskResponse")
}

// ---- gRPC Service ----
type MsgServer interface {
	CreateTask(context.Context, *MsgCreateTask) (*MsgCreateTaskResponse, error)
	AssignTask(context.Context, *MsgAssignTask) (*MsgAssignTaskResponse, error)
	CompleteTask(context.Context, *MsgCompleteTask) (*MsgCompleteTaskResponse, error)
}

type UnimplementedMsgServer struct{}

func (*UnimplementedMsgServer) CreateTask(context.Context, *MsgCreateTask) (*MsgCreateTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTask not implemented")
}
func (*UnimplementedMsgServer) AssignTask(context.Context, *MsgAssignTask) (*MsgAssignTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AssignTask not implemented")
}
func (*UnimplementedMsgServer) CompleteTask(context.Context, *MsgCompleteTask) (*MsgCompleteTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompleteTask not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_CreateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateTask)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/mychain.taskreg.v1.Msg/CreateTask"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateTask(ctx, req.(*MsgCreateTask))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_AssignTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgAssignTask)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).AssignTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/mychain.taskreg.v1.Msg/AssignTask"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).AssignTask(ctx, req.(*MsgAssignTask))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CompleteTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCompleteTask)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CompleteTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/mychain.taskreg.v1.Msg/CompleteTask"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CompleteTask(ctx, req.(*MsgCompleteTask))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mychain.taskreg.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{MethodName: "CreateTask", Handler: _Msg_CreateTask_Handler},
		{MethodName: "AssignTask", Handler: _Msg_AssignTask_Handler},
		{MethodName: "CompleteTask", Handler: _Msg_CompleteTask_Handler},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mychain/taskreg/v1/tx.proto",
}
