// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mychain/taskreg/v1/types.proto
package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	"google.golang.org/protobuf/encoding/protowire"
	math "math"
)

var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

const _ = proto.GoGoProtoPackageIsVersion3

type TaskStatus int32

const (
	TaskStatus_TASK_STATUS_UNSPECIFIED TaskStatus = 0
	TaskStatus_TASK_STATUS_OPEN       TaskStatus = 1
	TaskStatus_TASK_STATUS_ASSIGNED   TaskStatus = 2
	TaskStatus_TASK_STATUS_COMPLETED  TaskStatus = 3
)

var TaskStatus_name = map[int32]string{
	0: "TASK_STATUS_UNSPECIFIED",
	1: "TASK_STATUS_OPEN",
	2: "TASK_STATUS_ASSIGNED",
	3: "TASK_STATUS_COMPLETED",
}

var TaskStatus_value = map[string]int32{
	"TASK_STATUS_UNSPECIFIED": 0,
	"TASK_STATUS_OPEN":       1,
	"TASK_STATUS_ASSIGNED":   2,
	"TASK_STATUS_COMPLETED":  3,
}

func (x TaskStatus) String() string {
	return proto.EnumName(TaskStatus_name, int32(x))
}

type Task struct {
	Id          uint64     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title       string     `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description string     `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Creator     string     `protobuf:"bytes,4,opt,name=creator,proto3" json:"creator,omitempty"`
	Assignee    string     `protobuf:"bytes,5,opt,name=assignee,proto3" json:"assignee,omitempty"`
	Status      TaskStatus `protobuf:"varint,6,opt,name=status,proto3,enum=mychain.taskreg.v1.TaskStatus" json:"status,omitempty"`
}

func (m *Task) Reset()                       { *m = Task{} }
func (m *Task) String() string               { return fmt.Sprintf("Task{id:%d,title:%s}", m.Id, m.Title) }
func (m *Task) ProtoMessage()                {}
func (*Task) Descriptor() ([]byte, []int)    { return fileDescriptor_types, []int{0} }

func (m *Task) GetId() uint64          { return m.Id }
func (m *Task) GetTitle() string       { return m.Title }
func (m *Task) GetDescription() string { return m.Description }
func (m *Task) GetCreator() string     { return m.Creator }
func (m *Task) GetAssignee() string    { return m.Assignee }
func (m *Task) GetStatus() TaskStatus  { return m.Status }

func (m *Task) Marshal() ([]byte, error) {
	b := make([]byte, 0, m.Size())
	b = appendUint64(b, 1, m.Id)
	b = appendString(b, 2, m.Title)
	b = appendString(b, 3, m.Description)
	b = appendString(b, 4, m.Creator)
	b = appendString(b, 5, m.Assignee)
	if m.Status != 0 {
		b = protowire.AppendTag(b, 6, protowire.VarintType)
		b = protowire.AppendVarint(b, uint64(m.Status))
	}
	return b, nil
}

func (m *Task) MarshalTo(dAtA []byte) (int, error) {
	bz, err := m.Marshal()
	if err != nil {
		return 0, err
	}
	copy(dAtA, bz)
	return len(bz), nil
}

func (m *Task) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	bz, err := m.Marshal()
	if err != nil {
		return 0, err
	}
	copy(dAtA[len(dAtA)-len(bz):], bz)
	return len(bz), nil
}

func (m *Task) Size() int {
	n := sizeUint64(1, m.Id)
	n += sizeString(2, m.Title)
	n += sizeString(3, m.Description)
	n += sizeString(4, m.Creator)
	n += sizeString(5, m.Assignee)
	if m.Status != 0 {
		n += protowire.SizeTag(6) + protowire.SizeVarint(uint64(m.Status))
	}
	return n
}

func (m *Task) Unmarshal(b []byte) error {
	for len(b) > 0 {
		num, typ, n := protowire.ConsumeTag(b)
		if n < 0 {
			return fmt.Errorf("bad tag")
		}
		b = b[n:]
		switch num {
		case 1:
			v, n := protowire.ConsumeVarint(b)
			if n < 0 {
				return fmt.Errorf("bad varint")
			}
			m.Id = v
			b = b[n:]
		case 2:
			v, n := protowire.ConsumeString(b)
			if n < 0 {
				return fmt.Errorf("bad string")
			}
			m.Title = v
			b = b[n:]
		case 3:
			v, n := protowire.ConsumeString(b)
			if n < 0 {
				return fmt.Errorf("bad string")
			}
			m.Description = v
			b = b[n:]
		case 4:
			v, n := protowire.ConsumeString(b)
			if n < 0 {
				return fmt.Errorf("bad string")
			}
			m.Creator = v
			b = b[n:]
		case 5:
			v, n := protowire.ConsumeString(b)
			if n < 0 {
				return fmt.Errorf("bad string")
			}
			m.Assignee = v
			b = b[n:]
		case 6:
			v, n := protowire.ConsumeVarint(b)
			if n < 0 {
				return fmt.Errorf("bad varint")
			}
			m.Status = TaskStatus(v)
			b = b[n:]
		default:
			var err error
			b, err = skipField(b, typ)
			if err != nil {
				return err
			}
		}
	}
	return nil
}

func init() {
	proto.RegisterEnum("mychain.taskreg.v1.TaskStatus", TaskStatus_name, TaskStatus_value)
	proto.RegisterType((*Task)(nil), "mychain.taskreg.v1.Task")
}
